import { chromium } from "playwright";
const selector = process.argv[2] || "#how-it-works";
const out = process.argv[3] || "/tmp/mobile.png";
const base = process.argv[4] || "http://localhost:4321/";
const browser = await chromium.launch({ channel: "chrome" });
const page = await browser.newPage({ viewport: { width: 414, height: 900 }, deviceScaleFactor: 2 });
await page.goto(base, { waitUntil: "networkidle" });
await page.evaluate(() => document.fonts.ready);
const el = page.locator(selector).first();
await el.scrollIntoViewIfNeeded();
await page.waitForTimeout(1600);
await el.screenshot({ path: out });
console.log("mobile shot", selector, "->", out);
await browser.close();
